name: Auto Merge from Upstream

on:
  schedule:
    - cron: '0 3 * * *'  # 每天凌晨3点（UTC）执行，可改为其他时间
  workflow_dispatch:      # 可手动触发

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Your Repo
        uses: actions/checkout@v4

      - name: Set Git User
        run: |
          git config --global user.name "pencilheart"
          git config --global user.email "495474804@qq.com"

      - name: Add Upstream and Fetch
        run: |
          git remote add upstream https://github.com/mihomo-party-org/override-hub.git
          git fetch upstream

      - name: Merge Upstream/main into Your main
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories --no-edit || echo "No merge needed"
          git push origin main
